name: API Tests
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python3-pip

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Start FastAPI server
              run: python apiserver.py &
              env:
                  PYTHONUNBUFFERED: 1

            - name: Wait for server to be ready
              run: sleep 5 # Wait to ensure the server is up

            - name: Run unit tests with coverage
              run: |
                  pytest automation_test_pytest.py -v \
                    --cov=apiserver \
                    --html=report.html \
                    --self-contained-html \
                    --alluredir=./allure-results

            - name: Run performance tests
              run: |
                  locust -f performance_test.py \
                    --host=http://localhost:8000 \
                    --users 10 \
                    --spawn-rate 1 \
                    --run-time 1m \
                    --headless

            - name: Upload test report
              uses: actions/upload-artifact@v2
              with:
                  name: test-report
                  path: report.html

            - name: Upload allure results
              uses: actions/upload-artifact@v2
              with:
                  name: allure-results
                  path: ./allure-results
